### ISSUE TITLE
Missing requirements in the doc

### ISSUE THREAD

**Issue by chevdor** [mh-dev/esp32_reusable_components#1]
I am getting the following error:
`/Users/.../esp32_reusable_components/custom-components/main/./main.c:2:19: fatal error: unity.h: No such file or directory`

**Comment by mh-dev** [comment]
What did you execute to come to that? 
Did you make sure to set the EXTRA_COMPONENT_DIRS environment variable properly? The version I mentioned in the description is not suitable if you set it via windows in the system settings. This one is used as a shell script added to my mysys installation.

You can verify this by printenv EXTRA_COMPONENT_DIRS in the mysys shell. This should display the full path to the folder with the replaced IDF_PATH variable.

**Comment by chevdor** [comment]
Since it was not in the doc, I did not clone inside EXTRA_COMPONENT_DIRS.
I will test again, thanks for updating the doc!

**Comment by mh-dev** [comment]
Is it now working for you?

**Comment by chevdor** [comment]
hi @mh-dev, almost. Using the correct export, your code compiles find.
There must be however an issue in the/my build process.
Using `make TESTS_ALL=1 `and flashing, I can see the full list of tests, including your.
Using a `make clean` + `make TEST_COMPONENTS='awesome_component'` and flashing, the list is empty.

**Comment by mh-dev** [comment]
I performed the same steps and everything is working for me. 
I am not sure what the root cause of your problem is. You can try to delete the build directory unfortunately make clean does not remove its content and try it again.

**Comment by chevdor** [comment]
@mh-dev deleting the build folder definitely helps.

Strangely:
`make clean && rm -rf && make TEST_COMPONENTS='awesome_component awesome_component_cpp' && make flash && make monitor` works

but
`make clean && rm -rf && make TEST_COMPONENTS='awesome_component' && make flash && make monitor` followed by `make clean && rm -rf && make TEST_COMPONENTS='awesome_component_cpp' && make flash && make monitor`
shows only the first component.

I am closing anyway here because I think your code works fine. Thanks again!
