### ISSUE TITLE
Sample app does not compile

### ISSUE THREAD

**Issue by chevdor** [mh-dev/esp32_reusable_components#2]
From the app folder:
`make clean && rm -rf build && make`

```
CC app.o
/Users/.../esp32_reusable_components/app/main/./app.c:2:31: fatal error: awesome_component.h: No such file or directory
```

**Comment by mh-dev** [comment]
Seems that you did not set env variable `EXTRA_COMPONENT_DIRS` properly

**Comment by chevdor** [comment]
Worked too late at night... working all good and as you said probably an issue with EXTRA_COMPONENT_DIRS

**Comment by mh-dev** [comment]
Glad that your problems are solved. I hope this approach is what you need.

**Comment by chevdor** [comment]
That´s perfect, thanks a lot for your help with that.
